### ISSUE TITLE
Cannot read the PID of the Elasticsearch process from the pid file in directory "target/elasticsearch0"

### ISSUE THREAD

**Issue by Creighton-Shepard** [alexcojocaru/elasticsearch-maven-plugin#116]
Hello, 
First, thanks for this plugin. It's really helpful for my Maven tests. 
I use it in its version `6.17` on Windows with the command `mvn test` or when doing a `mvn clean deploy`.

For it, I use almost the same configuration as described in the readme.md : 

```maven
<plugin>
    <groupId>com.github.alexcojocaru</groupId>
    <artifactId>elasticsearch-maven-plugin</artifactId>
    <version>6.17</version>
    <configuration>
        <version>6.8.5</version>
        <clusterName>insights</clusterName>
        <logLevel>DEBUG</logLevel>
    </configuration>
    <executions>
        <execution>
            <id>start-embedded-elasticsearch</id>
            <phase>test-compile</phase>
            <goals>
                <goal>runforked</goal>
            </goals>
        </execution>
        <execution>
            <id>stop-embedded-elasticsearch</id>
            <phase>test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

I have a small problem with it. In the end of the tests, I always have this StackTrace : 

```
[INFO] Cleaning up at application shutdown...
[DEBUG] Cannot read the PID from file; assuming the process is not running
java.lang.IllegalStateException: Cannot read the PID of the Elasticsearch process from the pid file in directory 'C:\Users\I500638\Documents\SAPDevelop\Insights\project\insight\backend\paurt-service\target\elasticsearch0'
        at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.getElasticsearchPid(ProcessUtil.java:109)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateWindowsProcess(ForkedElasticsearchProcessDestroyer.java:86)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateProcess(ForkedElasticsearchProcessDestroyer.java:65)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.access$000(ForkedElasticsearchProcessDestroyer.java:15)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer$1.run(ForkedElasticsearchProcessDestroyer.java:28)
Caused by: java.nio.file.NoSuchFileException: C:\Users\I500638\Documents\SAPDevelop\Insights\project\insight\backend\paurt-service\target\elasticsearch0\pid
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.getElasticsearchPid(ProcessUtil.java:103)
        ... 4 more

```

However, everything is working fine, and the build and deploy of my microapplications seems to work fine. 
It's just that it's returning an error at the end, and it's gonna be hard to automate it in a Jenkins for example.

**Comment by alexcojocaru** [comment]
As you can see, that exception is logged on the DEBUG level. It's more of an unexpected state, but the plugin can recover from it: https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/master/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/ForkedElasticsearchProcessDestroyer.java#L91

If everything else goes well, the mvn process will succeed. If you check the process exit code, it should be 0, and that's what Jenkins uses to determine whether the execution was successful or not.

I hope this helps.

**Comment by alexcojocaru** [comment]
Closing due to inactivity.
