### ISSUE TITLE
Cannot delete download directory for 8.x with plugin 6.20

### ISSUE THREAD

**Issue by ChrisSamo632** [alexcojocaru/elasticsearch-maven-plugin#141]
I see the following warning in the logs when using plugin version `6.20` with Elasticsearch `8.0.1`:

```java
[INFO] Installing /tmp/elasticsearch-8.0.1-linux-x86_64.tar.gz to ....m2/repository/com/github/alexcojocaru/elasticsearch/8.0.1/elasticsearch-8.0.1-linux-x86_64.tar.gz
[INFO] [stdout] [ERROR] Could not delete Elasticsearch unpack directory :
[INFO] [stdout] java.io.IOException: Unable to delete directory /tmp/454a7afd-b868-430b-bd7f-bbfcea2ccf41.
[INFO] [stdout]         at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1127)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.cleanUp(ResolveElasticsearchStep.java:54)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.step.ResolveElasticsearchStep.execute(ResolveElasticsearchStep.java:44)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.lambda$execute$0(DefaultInstanceStepSequence.java:21)
[INFO] [stdout]         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultInstanceStepSequence.execute(DefaultInstanceStepSequence.java:21)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedInstance.configureInstance(ForkedInstance.java:33)
[INFO] [stdout]         at com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo.execute(RunForkedMojo.java:43)
[INFO] [stdout]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[INFO] [stdout]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:271)
[INFO] [stdout]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:196)
[INFO] [stdout]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
[INFO] [stdout]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO] [stdout]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[INFO] [stdout]         at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
[INFO] [stdout]         at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
[INFO] [stdout]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[INFO] [stdout]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[INFO] [stdout]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[INFO] [stdout]         at java.base/java.lang.Thread.run(Thread.java:829)
```

Not a big problem as the 8.x download is successful and works without issue, but the warning and dangling directory would be good to clean up if possible.

Note that I'm using [mvnd](https://github.com/apache/maven-mvnd) here rather than standard Maven, if that makes a difference.

**Comment by alexcojocaru** [comment]
Fixed; I am about to release a newer version which includes the fix for this.
