### ISSUE TITLE
Cannot run program /pid

### ISSUE THREAD

**Issue by statut** [alexcojocaru/elasticsearch-maven-plugin#22]
When integration tests stop, plugin throws the following exception:

`[INFO]
[INFO] --- jetty-maven-plugin:8.1.3.v20120416:stop (stop-jetty) @  ---
[INFO]
Stopping server 0
[INFO] --- elasticsearch-maven-plugin:5.0:stop (stop-elasticsearch) @  ---
[INFO] Stopping Elasticsearch [com.github.alexcojocaru.mojo.elasticsearch.v2.InstanceConfiguration@34d6bca6[id=0,baseDir=D:\work\...\target\elasticsearch0,httpPort=0,transportPort=0,pathData=<null>,pathLogs=<null>]]
[ERROR] Exception while stopping Elasticsearch
java.io.IOException: Cannot run program "/pid" (in directory "D:\work\...\target\elasticsearch0"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.StopMojo.execute(StopMojo.java:50)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)                                                                                                                                                       16:35Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 23 more`

Windows 7x64.

What is the cause of that? Thanks.

**Comment by statut** [comment]
Maybe "taskkill" should be added [here](https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/690d8dcc2e2b230c9aa4c5484f74ee56fd7ba029/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/StopMojo.java#L82)

**Comment by alexcojocaru** [comment]
You seem to be right; the arguments to kill the ES process are there, but the actual cmd is missing :)
I am going to fix it shortly and release a new version. Stay tuned.

**Comment by alexcojocaru** [comment]
New version 5.1 has been released. Let me know how it works; I am going to close this issue for now.

**Comment by statut** [comment]
Could you, please, also add "/F" flag to the taskkill command? Without that flag JVM isn't killed.

**Comment by alexcojocaru** [comment]
Since I am not able to test the plugin on windows, can you fix the issue and create a merge request? All you need is to clone the project locally, add that extra arg to the cmd array, and run `mvn clean verify` to verify that the fix is working properly.

**Comment by statut** [comment]
Okay, I will do it on this weekend

пт, 23 дек. 2016 г., 19:22 alexcojocaru <notifications@github.com>:

**Comment by statut** [comment]
I've created a pull request #24.

Is it possible to add a property to configure a timeout of ElasticSearch client when the client run init scripts? Default timeout is 1 second as I see but I often get error "SocketTimeoutException" during initialization. Thanks.

**Comment by alexcojocaru** [comment]
I merged your pull request into the main branch. Thanks for the patch.

Can you open a separate issue for the timeout exception? I find that very odd, for it's a connection to localhost, and 1000 is plenty for making such a request. Unless the ES instance is very very slow, or the command to execute is time consuming.

**Comment by alexcojocaru** [comment]
I released version 5.2 earlier, which includes your fix. Thanks again.
