### ISSUE TITLE
No implementation for org.eclipse.aether.RepositorySystem was bound

### ISSUE THREAD

**Issue by defnull** [alexcojocaru/elasticsearch-maven-plugin#28]
I am getting this error:

    WARNUNG: Error injecting: com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo
    com.google.inject.ProvisionException: Guice provision errors:

    1) No implementation for org.eclipse.aether.RepositorySystem was bound.
      while locating com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo

    1 error
	    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:999)
	    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1025)
	    at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	    at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	    at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	    at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	    at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1036)
	    at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	    at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	    at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	    at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	    at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	    at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:498)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

With the maven version shipped with Ubuntu 14.04 LTS

    mvn --version
    Apache Maven 3.0.5
    Maven home: /usr/share/maven
    Java version: 1.8.0_121, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-8-oracle/jre
    Default locale: de_DE, platform encoding: UTF-8
    OS name: "linux", version: "3.16.0-38-generic", arch: "amd64", family: "unix"

Is there any change to make this plugin compatible to the 3.0 branch of maven?

**Comment by alexcojocaru** [comment]
From https://wiki.eclipse.org/Aether/Using_Aether_in_Maven_Plugins: `Maven 3.1.0 is the earliest version using Eclipse Aether, Maven 3.0.x uses the incompatible predecessor Sonatype Aether`

It is possible to switch to the Sonatype Aether (which I believe is deprecated and still supported by newer versions of Maven). I can probably take a look at this, although I cannot commit to anything in the near future.

**Comment by alexcojocaru** [comment]
I fixed this issue in the es5-maven30 branch: https://github.com/alexcojocaru/elasticsearch-maven-plugin/tree/es5-maven30. I am refraining from releasing this branch for the time being, for a couple of reasons:
* going forward, the new aether API is the way to go; the old sonatype aether has been discotinued in 2011;
* I don't want to maintain an additional branch just to support maven 3.0; that would create extra work when releasing new version of the plugin, when applying patches and when adding new features;
* there doesn't seem to be much demand for maven 3.0 support.

If there is a way to configure this fix as a separate module on the project, in order to automate adding new feature, patches and releasing new version, let me know.

**Comment by alexcojocaru** [comment]
Everything seems to be against adding support for Maven 3.0.
The build on the feature branch failed in Travis:
https://travis-ci.org/alexcojocaru/elasticsearch-maven-plugin/builds/201322174

That is because Travis uses `Apache Maven 3.2.5` for building Java projects and it does not provide support for customizing the Maven version: https://docs.travis-ci.com/user/languages/java/#Projects-Using-Maven.

**Comment by defnull** [comment]
Is there a way to catch that injection error and provide a more helpful error message? That would be totally fine I think. Or make sure the error message is google-able (perhaps a warning in the readme?)

**Comment by alexcojocaru** [comment]
Sure. I will add a note to the README to describe the limitation.
If google indexed this page already, then the error is google-able (thanks to you).

**Comment by defnull** [comment]
Thanks for your great plugin by the way. It makes integration-testing A LOT easier, especially since elasticsearch dropped support for embedded nodes a while ago.

**Comment by bradford-scott** [comment]
@alexcojocaru I am unable to path to multiple initialization scripts as when I attempt to do so using the pathInitScript tag it throws an error stating the path to the script is invalid when it isn't.  If i have a singular script it is fine

**Comment by alexcojocaru** [comment]
I will give this a try later and get back to you.
In the meanwhile, could you tell me which maven version you are using?

**Comment by alexcojocaru** [comment]
There is an automated test for this use case:
https://github.com/alexcojocaru/elasticsearch-maven-plugin/tree/master/src/it/runforked-with-init-scripts
and it's been passing consistently.

**Comment by bradford-scott** [comment]
Hi, I am using maven version 3.6.0

Maven is throwing an error stating the path is invalid no matter how I try
to set it up.  I have also tried using pathConf to call json files to
populate documents in the index without success.  Still learning :)

Thanks,
Brad

**Comment by bradford-scott** [comment]
However my failsafe plugin version is 2.15.

**Comment by bradford-scott** [comment]
Here is the error:
Execution start-elasticsearch of goal
com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked failed:
The provided init script path is not a valid file path:
src/test/resources/elasticsearch/es_initialization_script.json,
[ERROR]
src/test/resources/elasticsearch/document1.json

**Comment by alexcojocaru** [comment]
That error does not seem related to `org.eclipse.aether.RepositorySystem`

Could you double check that the file path in the error message matches the file you have in the project?
Try enabling the `DEBUG` level logging on the plugin (using the logLevel property, see the doc for details), and see if that gives you more details.

**Comment by bradford-scott** [comment]
I will do that, I am running this in intelliJ does that matter?

**Comment by alexcojocaru** [comment]
I don't know, could be related. It would help if you run from the cmd line, as that's reproducible on my end.

**Comment by bradford-scott** [comment]
When i run it with a single initialization script it works fine, but when i
try to put in a comma delimited list to separate out the json requests it
throws an error, almost like it isn't parsing the list into separate
runnable requests

**Comment by bradford-scott** [comment]
plugin def:

<plugin>
    <groupId>com.github.alexcojocaru</groupId>
    <artifactId>elasticsearch-maven-plugin</artifactId>
    <version>6.13</version>
    <configuration>
        
        <version>6.6.0</version>
        <clusterName>integration-test-cluster</clusterName>
        <transportPort>9300</transportPort>
        <httpPort>9200</httpPort>
        <pathInitScript>
            src/test/resources/elasticsearch/es_initialization_script.json,
            src/test/resources/elasticsearch/script2.json
        </pathInitScript>
    </configuration>
    <executions>
        
        <execution>
            <id>start-elasticsearch</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>runforked</goal>
            </goals>
        </execution>
        <execution>
            <id>stop-elasticsearch</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>



Debug log from time of error:

[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  29.034 s
[INFO] Finished at: 2020-07-14T12:43:54-05:00
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked
(start-elasticsearch) on project provider-carrier-entity-search-api:
Execution start-elasticsearch of goal
com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked failed:
The provided init script path is not a valid file path:
src/test/resources/elasticsearch/es_initialization_script.json,
[ERROR]
src/test/resources/elasticsearch/script2.json
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute
goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked
(start-elasticsearch) on project provider-carrier-entity-search-api:
Execution start-elasticsearch of goal
com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked failed:
The provided init script path is not a valid file path:
src/test/resources/elasticsearch/es_initialization_script.json,
                        src/test/resources/elasticsearch/script2.json
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution
start-elasticsearch of goal
com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked failed:
The provided init script path is not a valid file path:
src/test/resources/elasticsearch/es_initialization_script.json,
                        src/test/resources/elasticsearch/script2.json
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
(DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:356)
Caused by:
com.github.alexcojocaru.mojo.elasticsearch.v2.ElasticsearchSetupException:
The provided init script path is not a valid file path:
src/test/resources/elasticsearch/es_initialization_script.json,
                        src/test/resources/elasticsearch/script2.json
    at
com.github.alexcojocaru.mojo.elasticsearch.v2.step.BootstrapClusterStep.validateFile
(BootstrapClusterStep.java:71)
    at
com.github.alexcojocaru.mojo.elasticsearch.v2.step.BootstrapClusterStep.execute
(BootstrapClusterStep.java:45)
    at
com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultClusterStepSequence.lambda$execute$0
(DefaultClusterStepSequence.java:21)
    at java.lang.Iterable.forEach (Iterable.java:75)
    at
com.github.alexcojocaru.mojo.elasticsearch.v2.step.DefaultClusterStepSequence.execute
(DefaultClusterStepSequence.java:21)
    at com.github.alexcojocaru.mojo.elasticsearch.v2.RunForkedMojo.execute
(RunForkedMojo.java:56)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
(DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:356)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[INFO] Cleaning up at application shutdown...
[INFO] The Elasticsearch process is still running; stopping it ...
[INFO] ... the Elasticsearch process [0] has stopped. Exit code: 143

>

**Comment by defnull** [comment]
> @alexcojocaru I am unable to path to multiple initialization scripts as when I attempt to do so using the pathInitScript tag it throws an error stating the path to the script is invalid when it isn't. If i have a singular script it is fine

Why are you discussing a completely unrelated issue here?

**Comment by alexcojocaru** [comment]
> That error does not seem related to `org.eclipse.aether.RepositorySystem`
> 

There's nothing in the plugin output above that would be related to the original issue. @bradford-scott please open a separate issue, and add the plugin output to it, and let's continue the discussion there.

**Comment by dummyelastic** [comment]
@alexcojocaru  is it possible to make it work for gradle also or if there is anything already existing for gradle?
