### ISSUE TITLE
Memory Issue when starting

### ISSUE THREAD

**Issue by sja** [alexcojocaru/elasticsearch-maven-plugin#51]
Hi!

Environment: Windows 7

```
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Exception in thread "Thread-1" java.lang.IllegalStateException: This Elasticsearch process destroyer does not support this operation
    at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.remove(ForkedElasticsearchProcessDestroyer.java:68)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:411)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
    at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:109)
    at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedInstance.run(ForkedInstance.java:39)
    at java.lang.Thread.run(Thread.java:748)
[DEBUG] Waiting  up to 30s for Elasticsearch to start ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:38 min
[INFO] Finished at: 2017-10-20T11:19:45+03:00
[INFO] Final Memory: 28M/67M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:5.10:runforked (start-elasticsearch) on project mrc-credit-limit: Condition returned by method "waitToStart" in class com.github.alexcojocaru.mojo.elasticsearch.v2.client.Monitor was not fulfilled within 30 seconds. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] The Elasticsearch process has already stopped. Nothing to clean up

Process finished with exit code 1
```

## pom.xml
```
<plugin>
	<groupId>com.github.alexcojocaru</groupId>
	<artifactId>elasticsearch-maven-plugin</artifactId>
	<version>5.10</version>
	<configuration>
		<clusterName>creditlimit</clusterName>
		<transportPort>9300</transportPort>
		<httpPort>9200</httpPort>
		<version>5.5.2</version>
	</configuration>
	<executions>
		<execution>
			<id>start-elasticsearch</id>
			<phase>compile</phase>
			<goals>
				<goal>runforked</goal>
			</goals>
		</execution>
		<execution>
			<id>stop-elasticsearch</id>
			<phase>prepare-package</phase>
			<goals>
				<goal>stop</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by dadoonet** [comment]
Yeah. Elasticsearch by default requires 2gb free memory. I think you can control that with a system property though. ES_JAVA_OPTS

See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

**Comment by alexcojocaru** [comment]
Thanks for answering that, @dadoonet. You saved me some research.

@sja The `pathConf` property of the plugin should help you with setting the Xms/Xmx. If you need help with using it, let me know.
