### ISSUE TITLE
Provide some example project

### ISSUE THREAD

**Issue by cselti** [alexcojocaru/elasticsearch-maven-plugin#64]
I try to execute the given example projects in the src/it directory using the version 6.5 of the maven module (maven version is 3.3.9), but the tests are halting on the same error (Caused by: java.io.FileNotFoundException: test.properties (The file or the directory not exists). For example:

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/src/test/resources
[INFO] 
[INFO] --- elasticsearch-maven-plugin:6.5:runforked (run) @ test ---
[INFO] Using Elasticsearch [0] configuration: com.github.alexcojocaru.mojo.elasticsearch.v2.InstanceConfiguration@61942c1[id=0,baseDir=/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0,httpPort=9200,transportPort=9300,pathData=<null>,pathLogs=<null>,settings=<null>]
Downloading: https://oss.sonatype.org/content/groups/public/org/elasticsearch/distribution/zip/elasticsearch/6.0.0/elasticsearch-6.0.0.zip
Downloaded: https://oss.sonatype.org/content/groups/public/org/elasticsearch/distribution/zip/elasticsearch/6.0.0/elasticsearch-6.0.0.zip (27401 KB at 2006.0 KB/sec)
[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch-plugin]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[sed, -i, -e, 1s:.*:#!/usr/bin/env bash:, bin/elasticsearch-plugin]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch-plugin, list]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[sed, -i, -e, 1s:.*:#!/usr/bin/env bash:, bin/elasticsearch]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch, -p, pid, -Ecluster.name=test, -Ehttp.port=9200, -Etransport.tcp.port=9300, -Ehttp.cors.enabled=true]' in directory '/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0'
[2018-06-14T11:16:08,049][INFO ][o.e.n.Node               ] [] initializing ...
[2018-06-14T11:16:08,852][INFO ][o.e.e.NodeEnvironment    ] [GqvgITe] using [1] data paths, mounts [[/home (/dev/nvme0n1p4)]], net usable_space [16.7gb], net total_space [176gb], types [ext4]
[2018-06-14T11:16:08,857][INFO ][o.e.e.NodeEnvironment    ] [GqvgITe] heap size [990.7mb], compressed ordinary object pointers [true]
[2018-06-14T11:16:08,871][INFO ][o.e.n.Node               ] node name [GqvgITe] derived from node ID [GqvgITeLQVW62jbZ6tfX-A]; set [node.name] to override
[2018-06-14T11:16:08,879][INFO ][o.e.n.Node               ] version[6.0.0], pid[20731], build[8f0685b/2017-11-10T18:41:22.859Z], OS[Linux/4.13.0-45-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_171/25.171-b11]
[2018-06-14T11:16:08,909][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0, -Des.path.conf=/home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/elasticsearch0/config]
[2018-06-14T11:16:12,697][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [aggs-matrix-stats]
[2018-06-14T11:16:12,698][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [analysis-common]
[2018-06-14T11:16:12,699][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [ingest-common]
[2018-06-14T11:16:12,701][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [lang-expression]
[2018-06-14T11:16:12,709][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [lang-mustache]
[2018-06-14T11:16:12,710][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [lang-painless]
[2018-06-14T11:16:12,711][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [parent-join]
[2018-06-14T11:16:12,711][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [percolator]
[2018-06-14T11:16:12,711][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [reindex]
[2018-06-14T11:16:12,712][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [repository-url]
[2018-06-14T11:16:12,712][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [transport-netty4]
[2018-06-14T11:16:12,713][INFO ][o.e.p.PluginsService     ] [GqvgITe] loaded module [tribe]
[2018-06-14T11:16:12,713][INFO ][o.e.p.PluginsService     ] [GqvgITe] no plugins loaded
[2018-06-14T11:16:14,399][INFO ][o.e.d.DiscoveryModule    ] [GqvgITe] using discovery type [zen]
[2018-06-14T11:16:15,230][INFO ][o.e.n.Node               ] initialized
[2018-06-14T11:16:15,231][INFO ][o.e.n.Node               ] [GqvgITe] starting ...
[2018-06-14T11:16:15,475][INFO ][o.e.t.TransportService   ] [GqvgITe] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-06-14T11:16:15,489][WARN ][o.e.b.BootstrapChecks    ] [GqvgITe] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2018-06-14T11:16:18,585][INFO ][o.e.c.s.MasterService    ] [GqvgITe] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {GqvgITe}{GqvgITeLQVW62jbZ6tfX-A}{Ac3eFxW0QRq1LSD6FFDlWw}{127.0.0.1}{127.0.0.1:9300}
[2018-06-14T11:16:18,590][INFO ][o.e.c.s.ClusterApplierService] [GqvgITe] new_master {GqvgITe}{GqvgITeLQVW62jbZ6tfX-A}{Ac3eFxW0QRq1LSD6FFDlWw}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {GqvgITe}{GqvgITeLQVW62jbZ6tfX-A}{Ac3eFxW0QRq1LSD6FFDlWw}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-06-14T11:16:18,609][INFO ][o.e.h.n.Netty4HttpServerTransport] [GqvgITe] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-06-14T11:16:18,610][INFO ][o.e.n.Node               ] [GqvgITe] started
[2018-06-14T11:16:18,627][INFO ][o.e.g.GatewayService     ] [GqvgITe] recovered [0] indices into cluster_state
[INFO] The Elasticsearch instance has started
[2018-06-14T11:16:19,305][WARN ][o.e.h.n.Netty4HttpServerTransport] [GqvgITe] caught exception while handling client http traffic, closing connection [id: 0x94b4441a, L:/127.0.0.1:9200 - R:/127.0.0.1:55440]
java.io.IOException: A kapcsolatot bontotta a távoli fél
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_171]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_171]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_171]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_171]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_171]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[INFO] The Elasticsearch cluster has started
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test ---
[2018-06-14T11:16:20,374][WARN ][o.e.h.n.Netty4HttpServerTransport] [GqvgITe] caught exception while handling client http traffic, closing connection [id: 0xc9767643, L:/127.0.0.1:9200 - R:/127.0.0.1:55442]
java.io.IOException: A kapcsolatot bontotta a távoli fél
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_171]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_171]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_171]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_171]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_171]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test ---
[INFO] Surefire report directory: /home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.alexcojocaru.mojo.elasticsearch.v2.DefaultsTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.076 sec <<< FAILURE!
com.github.alexcojocaru.mojo.elasticsearch.v2.DefaultsTest  Time elapsed: 0.075 sec  <<< ERROR!
java.lang.RuntimeException: Cannot load httpPort from test.properties
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ItBase.beforeClass(ItBase.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
        at org.mockito.internal.runners.SilentJUnitRunner.run(SilentJUnitRunner.java:39)
        at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
        at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:104)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.FileNotFoundException: test.properties (Nincs ilyen fájl vagy könyvtár)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ItBase.beforeClass(ItBase.java:36)
        ... 24 more

Results :

Tests in error: 
  com.github.alexcojocaru.mojo.elasticsearch.v2.DefaultsTest: Cannot load httpPort from test.properties

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.121 s
[INFO] Finished at: 2018-06-14T11:16:21+02:00
[INFO] Final Memory: 24M/262M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/totha/work/elastic-hunspell/elasticsearch-maven-plugin/src/it/runforked-defaults-es6/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] Cleaning up at application shutdown...
[INFO] The Elasticsearch process is still running; stopping it ...
[INFO] ... the Elasticsearch process [0] has stopped. Exit code: 143
`
Can you help me in, what the problem is?

Thanks in advance!
Adrian

**Comment by alexcojocaru** [comment]
Hi Adrian,

Those are not example projects, they are integration tests for the plugin. I have never tried and, from what you're saying, it looks like you cannot run the directly. Instead, they are executed through the main pom file. Read this section of the project README - https://github.com/alexcojocaru/elasticsearch-maven-plugin#integration-tests - and let me know if you need more information.

alex

**Comment by cselti** [comment]
Hi Alex!
Ok, I will try again by following the README doc. 
But some example projects could be useful (especially when you want to check, that this tool is usable for you or not) - I have changed the ticket's topic to this.
 
Regards,
Adrian

**Comment by alexcojocaru** [comment]
I re-read the  README file shown on the project's home page and I believe the examples / snippets are sufficient to get one started (presuming a basic knowledge of maven configuration).
