### ISSUE TITLE
The process with PID could not be terminated. The operation attempted is not supported.

### ISSUE THREAD

**Issue by rustyx** [alexcojocaru/elasticsearch-maven-plugin#74]
Sometimes the ES instance on Windows can't be killed, and the build fails :-(

May be related to an [unkillable state](https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/).

```
[INFO] com.github.alexcojocaru.mojo.elasticsearch.v2.ElasticsearchSetupException: Elasticsearch [0]: Cannot execute command '[taskkill, /F, /pid, 12340]' in directory 'C:\Projects\elasticsearch-maven-plugin\target\it\runforked-with-path-conf\target\elasticsearch0'
[INFO] Output:
[INFO]
[INFO] Error:
[INFO] ERROR: The process with PID 12340 could not be terminated.
[INFO] Reason: The operation attempted is not supported.
[INFO]
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:267)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:149)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateWindowsProcess(ForkedElasticsearchProcessDestroyer.java:118)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.terminateProcess(ForkedElasticsearchProcessDestroyer.java:65)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.access$000(ForkedElasticsearchProcessDestroyer.java:15)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer$1.run(ForkedElasticsearchProcessDestroyer.java:28)
[INFO] Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
[INFO]  at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
[INFO]  at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
[INFO]  at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:222)
[INFO]  ... 5 more
```

**Comment by alexcojocaru** [comment]
Fixed.
