### ISSUE TITLE
Windows 10: This Elasticsearch process destroyer does not support this operation at startup

### ISSUE THREAD

**Issue by jmrodriguez** [alexcojocaru/elasticsearch-maven-plugin#84]
This seems to be related to #69 but the error displayed in Windows environments is a bit different, so I thought it was worth a separate issue for reference and documentation in case other stumble on it.

This is the error I got on Windows 10

```[INFO] --- elasticsearch-maven-plugin:6.4:runforked (start-elasticsearch) @ marketplacecms ---
[INFO] Using Elasticsearch [0] configuration: com.github.alexcojocaru.mojo.elasticsearch.v2.InstanceConfiguration@1351f28[id=0,baseDir=D:\myproject\target\elasticsearc
h0,httpPort=9200,transportPort=9300,pathData=<null>,pathLogs=<null>,settings=<null>]
[INFO] Elasticsearch[0]: Executing command '[cmd, /c, bin\elasticsearch-plugin, list]' in directory 'D:\myproject\target\elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[cmd, /c, bin\elasticsearch, -p, pid, -Ecluster.name=esDevCluster, -Ehttp.port=9200, -Etransport.tcp.port=9300, -Ehttp.cors.enabled=true]' in dir
ectory 'D:\myproject\target\elasticsearch0'
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Exception in thread "Thread-5" java.lang.IllegalStateException: This Elasticsearch process destroyer does not support this operation
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedElasticsearchProcessDestroyer.remove(ForkedElasticsearchProcessDestroyer.java:50)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:411)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:222)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.util.ProcessUtil.executeScript(ProcessUtil.java:167)
        at com.github.alexcojocaru.mojo.elasticsearch.v2.ForkedInstance.run(ForkedInstance.java:42)
        at java.lang.Thread.run(Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2019-02-26T10:56:59-06:00
[INFO] Final Memory: 15M/37M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.4:runforked (start-elasticsearch) on project marketplacecms: Condition returned by method "waitToStartIns
tance" in class com.github.alexcojocaru.mojo.elasticsearch.v2.client.Monitor was not fulfilled within 60 seconds. -> [Help 1]
[ERROR]```

**Comment by jmrodriguez** [comment]
The same solution applied for #69 worked in this case:

> setting the set the `ES_JVM_OPTIONS` env variable to `-cp "./target/elasticsearch0/lib/*"` in my IDE's (IntelliJ) run configuration (or in the terminal before executing the run command) 

prevents the error from happening and interrupting the run process.

Perhaps this is also worth including in the README?

**Comment by alexcojocaru** [comment]
Thanks for reporting the issue and the workaround, I will add a note to the README.
